-- Import more TACO foods - Vegetais, Frutas, Carboidratos, Laticínios
INSERT INTO alimentos (nome, quantidade_referencia_g, kcal_por_referencia, ptn_por_referencia, cho_por_referencia, lip_por_referencia, origem_ptn, tipo_id, info_adicional)
SELECT nome, 100, kcal, ptn, cho, lip, origem_ptn, tipo_id, 'Fonte: TACO'
FROM (
  VALUES
    -- VEGETAIS
    ('Abóbora, cabotian, cozida', 48.04, 1.44, 10.76, 0.73, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Abóbora, cabotian, crua', 38.6, 1.75, 8.36, 0.54, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Agrião, cru', 16.58, 2.69, 2.25, 0.24, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Alface, americana, crua', 8.79, 0.61, 1.75, 0.13, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Alface, crespa, crua', 10.68, 1.35, 1.7, 0.16, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Alface, lisa, crua', 13.82, 1.69, 2.43, 0.12, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Alho, cru', 113.13, 7.01, 23.91, 0.22, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Alho-poró, cru', 31.51, 1.41, 6.88, 0.14, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Berinjela, cozida', 18.85, 0.68, 4.47, 0.15, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Berinjela, crua', 19.63, 1.22, 4.43, 0.1, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Beterraba, cozida', 32.15, 1.29, 7.23, 0.09, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Beterraba, crua', 48.83, 1.95, 11.11, 0.09, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Brócolis, cozido', 24.64, 2.13, 4.37, 0.46, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Brócolis, cru', 25.5, 3.64, 4.03, 0.27, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Cebola, crua', 39.42, 1.71, 8.85, 0.08, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Cenoura, cozida', 29.86, 0.85, 6.69, 0.22, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Cenoura, crua', 34.14, 1.32, 7.66, 0.17, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Chuchu, cozido', 18.54, 0.41, 4.79, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Chuchu, cru', 16.98, 0.7, 4.14, 0.06, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Couve-flor, cozida', 19.11, 1.24, 3.88, 0.27, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Couve-flor, crua', 22.56, 1.91, 4.52, 0.21, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Couve, manteiga, crua', 27.06, 2.87, 4.33, 0.55, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Couve, manteiga, refogada', 90.34, 1.67, 8.71, 6.59, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Espinafre, Nova Zelândia, cru', 16.1, 2, 2.57, 0.24, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Espinafre, Nova Zelândia, refogado', 67.25, 2.72, 4.24, 5.43, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Pepino, cru', 9.53, 0.87, 2.04, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Pimentão, amarelo, cru', 27.93, 1.22, 5.96, 0.44, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Pimentão, verde, cru', 21.29, 1.05, 4.89, 0.15, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Pimentão, vermelho, cru', 23.28, 1.04, 5.47, 0.15, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Quiabo, cru', 29.94, 1.92, 6.37, 0.3, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Repolho, branco, cru', 17.12, 0.88, 3.86, 0.14, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Repolho, roxo, cru', 30.91, 1.91, 7.2, 0.06, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Rúcula, crua', 13.13, 1.77, 2.22, 0.11, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Tomate, com semente, cru', 15.34, 1.1, 3.14, 0.17, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Vagem, crua', 24.9, 1.79, 5.35, 0.17, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    ('Abobrinha, italiana, cozida', 15.04, 1.12, 2.98, 0.2, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Vegetais')),
    
    -- FRUTAS
    ('Abacaxi, cru', 48.32, 0.86, 12.33, 0.12, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Acerola, crua', 33.46, 0.91, 7.97, 0.21, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Banana, da terra, crua', 128.02, 1.43, 33.67, 0.24, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Banana, maçã, crua', 86.81, 1.75, 22.34, 0.06, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Banana, nanica, crua', 91.53, 1.4, 23.85, 0.12, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Banana, prata, crua', 98.25, 1.27, 25.96, 0.06, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Goiaba, vermelha, com casca, crua', 54.17, 1.09, 13.01, 0.44, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Laranja, baía, crua', 45.44, 0.98, 11.47, 0.1, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Laranja, pêra, crua', 36.77, 1.04, 8.95, 0.13, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Limão, tahiti, cru', 31.82, 0.94, 11.08, 0.14, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Mamão, Formosa, cru', 45.34, 0.82, 11.55, 0.12, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Mamão, Papaia, cru', 40.16, 0.46, 10.44, 0.12, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Manga, Haden, crua', 63.5, 0.41, 16.66, 0.26, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Manga, Tommy Atkins, crua', 50.69, 0.86, 12.77, 0.22, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Maracujá, cru', 68.44, 1.99, 12.26, 2.1, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Maçã, Fuji, com casca, crua', 55.52, 0.29, 15.15, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Melancia, crua', 32.61, 0.88, 8.14, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Melão, cru', 29.37, 0.68, 7.53, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Morango, cru', 30.15, 0.89, 6.82, 0.31, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Pêra, Williams, crua', 53.31, 0.57, 14.02, 0.11, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Pêssego, Aurora, cru', 36.33, 0.82, 9.32, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Tangerina, Poncã, crua', 37.83, 0.85, 9.61, 0.07, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Uva, Itália, crua', 52.87, 0.75, 13.57, 0.2, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Kiwi, cru', 51.14, 1.34, 11.5, 0.63, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Jabuticaba, crua', 58.05, 0.61, 15.26, 0.13, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Graviola, crua', 61.62, 0.85, 15.84, 0.21, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Frutas')),
    ('Abacate', 96.15, 1.24, 6.03, 8.4, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    
    -- CARBOIDRATOS
    ('Batata, doce, cozida', 76.76, 0.64, 18.42, 0.09, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Batata, doce, crua', 118.24, 1.26, 28.2, 0.13, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Batata, inglesa, cozida', 51.59, 1.16, 11.94, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Batata, inglesa, crua', 64.37, 1.77, 14.69, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Batata, inglesa, frita', 267.16, 4.97, 35.64, 13.11, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Mandioca, cozida', 125.36, 0.57, 30.09, 0.3, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Mandioca, crua', 151.42, 1.13, 36.17, 0.3, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Mandioca, frita', 300.06, 1.38, 50.25, 11.2, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Inhame, cru', 96.7, 2.05, 23.23, 0.21, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Cará, cozido', 77.58, 1.53, 18.85, 0.11, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Farinha de Arroz', 366, 5.9, 80.1, 1.4, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Aveia Flocos', 352, 14.5, 57, 7.9, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Aveia Farelo', 246, 17.3, 66.2, 7.03, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Granola', 367, 9, 57.5, 6.7, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Pão francês', 310, 11, 52, 5, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Tapioca', 347, 0.18, 85, 0.2, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Pão de forma', 250, 7.8, 48, 3, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Pão pita (arabe ou sirio)', 275, 9, 56, 1.2, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Cuscuz (cozido com sal)', 113, 2.2, 25.3, 0.7, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Macarrão, instantâneo', 435.86, 8.79, 62.43, 17.24, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Lasanha, massa fresca, cozida', 163.76, 5.81, 32.52, 1.16, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Farinha, de mandioca, crua', 360.87, 1.55, 87.9, 0.28, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Fécula, de mandioca', 330.85, 0.52, 81.15, 0.28, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Polvilho, doce', 351.23, 0.43, 86.77, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Mel, de abelha', 309.24, 0, 84.03, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Açúcar, cristal', 386.85, 0.32, 99.61, 0, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Açúcar, mascavo', 368.55, 0.76, 94.45, 0.09, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Feijão, carioca, cozido', 76.42, 4.78, 13.59, 0.54, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Feijão, preto, cozido', 77.03, 4.48, 14.01, 0.54, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Lentilha, cozida', 92.64, 6.31, 16.3, 0.52, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    ('Grão-de-bico, cozido', 130, 8.86, 21.5, 2.1, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Carboidratos')),
    
    -- LATICÍNIOS
    ('Queijo, minas, frescal', 264.27, 17.41, 3.24, 20.18, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Queijo, mozarela', 329.87, 22.65, 3.05, 25.18, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Queijo, parmesão', 452.96, 35.55, 1.66, 33.53, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Queijo, prato', 359.88, 22.66, 1.88, 29.11, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Queijo, requeijão, cremoso', 256.58, 9.63, 2.43, 23.44, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Queijo, ricota', 139.73, 12.6, 3.79, 8.11, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Queijo Cottage', 196, 24, 6.4, 8.6, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Queijo Minas meia cura', 320.72, 21.21, 3.57, 24.61, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Iogurte, natural', 51.49, 4.06, 1.92, 3.04, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Iogurte, natural, desnatado', 41.49, 3.83, 5.77, 0.32, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Iogurte, sabor morango', 69.57, 2.71, 9.69, 2.33, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Leite, condensado', 312.57, 7.67, 57, 6.74, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Leite, de coco', 166.16, 1.01, 2.19, 18.36, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Creme de Leite', 221.48, 1.51, 4.51, 22.48, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Doce, de leite, cremoso', 306.31, 5.48, 59.49, 5.99, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    ('Chocolate, ao leite', 539.59, 7.22, 59.58, 30.27, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Laticínios')),
    
    -- LIPÍDEOS
    ('Azeite de oliva extra virgem', 884, 0, 0, 100, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Azeite de dendê', 884, 0, 0, 100, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Manteiga, com sal', 725.97, 0.41, 0.06, 82.36, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Manteiga, sem sal', 757.54, 0.4, 0, 86.04, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Margarina, com óleo hidrogenado', 596.12, 0, 0, 67.43, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Castanha-de-caju, torrada, salgada', 570.17, 18.51, 29.13, 46.28, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Castanha-do-Brasil', 642.96, 14.54, 15.08, 63.46, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Amendoim torrado salgado', 605.78, 22.48, 18.7, 53.96, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Amêndoa, torrada, salgada', 580.75, 18.55, 29.55, 47.32, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Pasta de amendoim', 588, 25, 20, 50, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Coco em pedaços ou ralado', 406.49, 3.69, 10.4, 41.98, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Gergelim, semente', 583.55, 21.16, 21.62, 50.43, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Linhaça, semente', 495.1, 14.08, 43.31, 32.25, 'Vegetal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos')),
    ('Bacon', 541, 37.04, 1.42, 41.78, 'Animal', (SELECT id FROM tipos_alimentos WHERE nome_tipo = 'Lipídeos'))
) AS t(nome, kcal, ptn, cho, lip, origem_ptn, tipo_id)
ON CONFLICT (nome) DO NOTHING;