// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cghzttbggklhuyqxzabq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnaHp0dGJnZ2tsaHV5cXh6YWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTU4MjksImV4cCI6MjA3MDE3MTgyOX0.h64J00FCvjOX86vhpdI3sTXXVRkoWfpYLS6jQWkuUx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});