const PAYMENT_STATUS_MAP = {
  PAYMENT_CREATED: 'PENDING',
  PAYMENT_UPDATED: null,
  PAYMENT_CONFIRMED: 'CONFIRMED',
  PAYMENT_RECEIVED: 'RECEIVED',
  PAYMENT_OVERDUE: 'OVERDUE',
  PAYMENT_DELETED: 'CANCELLED',
  PAYMENT_RESTORED: 'PENDING',
  PAYMENT_REFUNDED: 'REFUNDED',
  PAYMENT_REFUND_IN_PROGRESS: 'REFUND_IN_PROGRESS',
  PAYMENT_ANTICIPATED: 'RECEIVED',
  PAYMENT_RECEIVED_IN_CASH_UNDONE: 'PENDING',
};

const PAYMENT_WEBHOOK_EVENTS = [
  'PAYMENT_CREATED',
  'PAYMENT_UPDATED',
  'PAYMENT_CONFIRMED',
  'PAYMENT_RECEIVED',
  'PAYMENT_OVERDUE',
  'PAYMENT_DELETED',
  'PAYMENT_RESTORED',
  'PAYMENT_REFUNDED',
  'PAYMENT_REFUND_IN_PROGRESS',
  'PAYMENT_ANTICIPATED',
  'PAYMENT_RECEIVED_IN_CASH_UNDONE',
];

const CUSTOMER_WEBHOOK_EVENTS = [
  'CUSTOMER_CREATED',
  'CUSTOMER_UPDATED',
  'CUSTOMER_DELETED',
];

const SUBSCRIPTION_WEBHOOK_EVENTS = [
  'SUBSCRIPTION_CREATED',
  'SUBSCRIPTION_UPDATED',
  'SUBSCRIPTION_DELETED',
  'SUBSCRIPTION_INACTIVATED',
];

const ALL_WEBHOOK_EVENTS = [
  ...PAYMENT_WEBHOOK_EVENTS,
  ...SUBSCRIPTION_WEBHOOK_EVENTS,
];

/** Eventos válidos na API Asaas ao registar webhook (CUSTOMER_* não são aceites). */
const WEBHOOK_REGISTER_EVENTS = ALL_WEBHOOK_EVENTS;

const INBOX_STATUS = {
  RECEIVED: 'received',
  PROCESSING: 'processing',
  PROCESSED: 'processed',
  FAILED: 'failed',
  DEAD_LETTER: 'dead_letter',
};

const SYNC_STATUS = {
  SYNCED: 'synced',
  PENDING_OUTBOUND: 'pending_outbound',
  CONFLICT: 'conflict',
  ORPHAN: 'orphan',
};

const MAX_INBOX_ATTEMPTS = 5;
const INBOX_BATCH_SIZE = 25;
const INBOX_WORKER_INTERVAL_MS = 3000;

module.exports = {
  PAYMENT_STATUS_MAP,
  PAYMENT_WEBHOOK_EVENTS,
  CUSTOMER_WEBHOOK_EVENTS,
  SUBSCRIPTION_WEBHOOK_EVENTS,
  ALL_WEBHOOK_EVENTS,
  WEBHOOK_REGISTER_EVENTS,
  INBOX_STATUS,
  SYNC_STATUS,
  MAX_INBOX_ATTEMPTS,
  INBOX_BATCH_SIZE,
  INBOX_WORKER_INTERVAL_MS,
};
